### ISSUE TITLE
Comments are not displayed correctly

### ISSUE THREAD

**Issue by terminatorOST** [cyfung1031/Tabview-Youtube#1]
Hi!

About 70% of the long comments are getting cut to "...", and don't have the "Read More" button.
If I triple-click on the comment to select it, and then copy/paste - it inserts a complete comment. So it's out there somewhere, just no "Read More" button.

Is there a way to fix this?

Thank you! And thank you for an amazing script! YouTube has gotten much less cluttered :)

**Comment by cyfung1031** [comment]
> Hi!
> 
> About 70% of the long comments are getting cut to "...", and don't have the "Read More" button.
> If I triple-click on the comment to select it, and then copy/paste - it inserts a complete comment. So it's out there somewhere, just no "Read More" button.
> 
> Is there a way to fix this?
> 
> Thank you! And thank you for an amazing script! YouTube has gotten much less cluttered :)

Hi
Sorry that I don't know there is someone has commented here. 
Yep. I just also found this bug too. I updated the css file and it should be okay now.

You can also install the userscript version here: https://greasyfork.org/zh-TW/scripts/428651-tabview-youtube

**Comment by cyfung1031** [comment]
> Hi!
> 
> About 70% of the long comments are getting cut to "...", and don't have the "Read More" button.
> If I triple-click on the comment to select it, and then copy/paste - it inserts a complete comment. So it's out there somewhere, just no "Read More" button.
> 
> Is there a way to fix this?
> 
> Thank you! And thank you for an amazing script! YouTube has gotten much less cluttered :)

Please update to version 1.8.7. It should be okay now.
I believe this is the bug for webkit browsers. 
Anyway, I made my own preliminary solution to lessen the problem. 

Please tell me the result after your update :)

**Comment by terminatorOST** [comment]
Yes, it's OK now!
Thank you!
