### ISSUE TITLE
Youtube Genius Lyrics panel no longer showing after v4.1.30

### ISSUE THREAD

**Issue by geektron** [cyfung1031/Tabview-Youtube#10]
The last version where Youtube Genius Lyrics displayed a lyrics panel was v4.1.30. I've tried this on both Chrome and Firefox using tampermonkey and violentmonkey on Windows 10. 

Starting in v4.1.38, the small G icon is shown, and you can search and select a song as usual, but the actual lyrics are not displayed anywhere.

**Comment by cyfung1031** [comment]
Thanks for reporting. This bug is now fixed in v4.2.6. Please close this issue if it works for you.
