### ISSUE TITLE
Visible body's scrollbar without noticeable overflow content

### ISSUE THREAD

**Issue by prandleman** [cyfung1031/Tabview-Youtube#14]
I'm assuming the point of this is to have everything in one frame eliminating the need to scroll down. For some reason I get a scrollbar that only moves a few pixels. While back I believe I disabled did a test with only this userscript running and issue still seemed to happen on 1920x1080. 

If I use js console to inject something simple like `document.body.style.overflow = 'hidden';`, this works fine but the userscript executes after my attempt with and injector for both 'DOMContentLoaded' and 'load'. Any recommendations?

**Comment by cyfung1031** [comment]
I don't understand what is your problem regarding scrollbar....

Is there a UI bug due to this script?
Which scrollbar you mean?

**Comment by prandleman** [comment]
https://imgur.com/a/AoTgFwB

**Comment by Dark3n89** [comment]
> https://imgur.com/a/AoTgFwB
Bro 
Lol use element scanner via console and you will see empty youtube bullshit, simply remove it with css or script.. I using very old code of this project and only one change what i must do, is remove something like comment box (empty div) idk name now.

**Comment by cyfung1031** [comment]
> https://imgur.com/a/AoTgFwB

Let me give you the answer first.
You can use stylus or userscript to inject the following css rule to hide the scrollbar in the watch page.
```css
html.tabview-normal-player body {
  overflow-y: hidden;
}
```

This "bug" might appear to some browsers for some users in some PCs.
Perhaps YouTube is rolling out new features.
Therefore I would like to wait until I can experience this issue, then I can do the pinpoint fixing.

One possible cause is the cinematic effect.
You can try to disable it to see whether it helps or not.
![kr5llmaqik0jqs2lbtbwihydipy2](https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/a9ecfb61-217f-4090-a86a-2a29669d2a0c)
(But this should not happen in Google Chrome)


Also, you might try to update your browser if the version is not latest.

**Comment by cyfung1031** [comment]
As @Dark3n89 said, there could be some empty youtube bullshits. (no content but occupying the space)

@prandleman If you have found out the exact element(s) causing the issue, please let me know :) .

You might check [here](https://www.labnol.org/software/chrome-dev-tools-tutorial/28131/) to see how to use Chrome's DevTools to find out the empty block(s) in your page.

**Comment by cyfung1031** [comment]
No further information available for this issue.

**Comment by prandleman** [comment]
One of the first things I noticed was that when the scroll happens the container/frame that holds the bulk of the page (sorry I don't know proper css terms) seems to be pushing into the masthead container 
![chrome_NhpC72WfQ7](https://github.com/cyfung1031/Tabview-Youtube/assets/94949194/c739a630-2a41-44d6-8201-3ee83c8fd207)

**Comment by prandleman** [comment]
I figured this was a one off issue with my setup and I understand that it could be many things which is why I tried no extensions except ublock (no custom filters). Was this the intent of the userscript? Do all of you have everything confined to one no scroll page? btw, thank you for this. can tell you put lots of time into it

**Comment by cyfung1031** [comment]
1.

```
html.tabview-normal-player body {
  overflow-y: hidden;
}
```
should work for you. Did you try?


2.
from your recording suggested, the tab container size is okay. it is not due to its oversizing.
<img width="950" alt="Screen Shot 2023-08-05 at 9 37 51" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/d7d6fb52-e72b-4393-a8cc-93cac761ed56">

It seems to be something above the tab container and video.
(e.g. `ytd-app`, `div#content`, `ytd-page-manager`, `yt-watch-flexy`, `#columns`, and those children elements of them)
<img width="779" alt="Screen Shot 2023-08-05 at 9 43 45" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/1d74ad69-aafe-458f-b266-fbd19cd175bc">


3.
I cannot fix the problem that caused by unknown reason

4.
You might try to use https://greasyfork.org/scripts/457317-youtube-live-borderless
It might help.

**Comment by cyfung1031** [comment]
No further information available for this issue.
