### ISSUE TITLE
Video Release Date?

### ISSUE THREAD

**Issue by MintMain21** [cyfung1031/Tabview-Youtube#15]
It'd be nice to have the video's original upload date in the sidebar description.

**Comment by Dark3n89** [comment]
Eh  is really hard click on date under video for release date? :D
![image](https://github.com/cyfung1031/Tabview-Youtube/assets/48175529/0052f306-33dc-40e8-9462-3ac0382af46e)

**Comment by cyfung1031** [comment]
1. It is located below channel name. (YouTube's native design)
2. Click the simplified date format, it will convert to full date (YouTube's native design)
3. Tabview Youtube provides you a way to find out the detailed date&time of the video. Move your cursor onto the video title.

Upload Date is not and will not be shown inside tab container, unless YouTube's native design wants to combine it into the description field. In the current design, description is description, upload date&time is upload date&time.
