### ISSUE TITLE
YouTube disabled the traditional comments?

### ISSUE THREAD

**Issue by cyfung1031** [cyfung1031/Tabview-Youtube#16]
https://greasyfork.org/scripts/428651-tabview-youtube/discussions/195969

**Comment by Dark3n89** [comment]
I using your source into my standard offline extenssion and all work fine, try delete cookies 
![image](https://github.com/cyfung1031/Tabview-Youtube/assets/48175529/6f3a1eba-35e4-473e-8edd-89bea198116b)

**Comment by cyfung1031** [comment]
Confirmed the issue can be solved by using https://greasyfork.org/scripts/470428-youtube-experiment-flags-tamer
