### ISSUE TITLE
[Feature] Set Default Tab in Script instead of in cookies.

### ISSUE THREAD

**Issue by MintMain21** [cyfung1031/Tabview-Youtube#18]
It appears that the default tab setting is set in browser cookies instead of the script itself. This means that when using YouTube in Private Browsing or a different Firefox Container the tab will be Recommended Videos (instead of my preferred Video Info).

I would prefer it if this option was saved in the script itself so that this would be the default in all browsing sessions regardless of how cookies are saved.

**Comment by MintMain21** [comment]
Update: Found a part of the script where the default tab can be easily changed.

There's probably a way to make this more user-friendly (IE: A toggle towards the top where we choose a preferred tab followed by "if default-tab.includes [option] then default-tab=option).

![image](https://github.com/cyfung1031/Tabview-Youtube/assets/91362684/a6371b11-1807-4216-994b-532ff07e39ae)

**Comment by cyfung1031** [comment]
1. Update Tabview Youtube to >= v4.19.0
2. Install [Tabview Youtube Design Customization](https://greasyfork.org/scripts/467638-tabview-youtube-design-customization) >= v0.2.0

3.
<img width="292" alt="Screen Shot 2023-08-15 at 18 47 43" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/a45ae403-4876-4dec-9510-30f43e51972d">

**Comment by MintMain21** [comment]
Perhaps the additional script is helpful for the unrounding of buttons, but I'm not sure why it's a stylus script when, again, the request was to edit the options from within the same script. 

The solution I found earlier is all I wanted and needed. If there's a way to streamline that for inexperienced users that would be nice, but making an additional script just seems so unnecessary. 

If you want examples of scripts that present toggles like that, look up [Privacy Redirector](https://github.com/dybdeskarphet/privacy-redirector) and [Invidious Preferences](https://github.com/MintMain21/Invidious-Preferences-Userscript)
