### ISSUE TITLE
Comments are cut again

### ISSUE THREAD

**Issue by terminatorOST** [cyfung1031/Tabview-Youtube#2]
Well, it lasted 5 days :(
But now it's back to ...
Maybe it's because of the recent browser update?
I'm using Firefox.

**Comment by cyfung1031** [comment]
I updated the css styling again. Please update to v1.8.11 and try.

**Comment by terminatorOST** [comment]
Nope, doesn't work :(

https://pastebin.com/W2d0Qhhe
I have mixed comments from one of the pages. Maybe you'll be able to spot, maybe some character doesn't trigger it?

**Comment by terminatorOST** [comment]
Yes, it works :)
(Had to clear the cache after the update of the script before testing it, led me to believe that it doesn't work for a moment)
Thank you again!
