### ISSUE TITLE
[bug]特定のズーム率において、プログレスバーの表示が狂う

### ISSUE THREAD

**Issue by ni1chigo2115** [cyfung1031/Tabview-Youtube#21]
![tvy_zoom_bugs](https://github.com/cyfung1031/Tabview-Youtube/assets/23652237/97727d50-9beb-46de-a49e-0cecd8348b46)
特定のサイズにおいて、プログレスバーがくるってしまうようです
プログレスバーとしては機能していますが、見た目と一致しないので使い勝手が悪くなっています

**Comment by Dark3n89** [comment]
Is new ANTI ADB system on chromium browsers, not problem with this script. Many browsers work on chromium, except brave browser example.

**Comment by ni1chigo2115** [comment]
vivaldi

**Comment by cyfung1031** [comment]
Not Caused by Tabview Youtube.

**Comment by ni1chigo2115** [comment]
ADSを無効化しましたが、プログレスバーの不具合は修正されませんでした

**Comment by cyfung1031** [comment]
> ABS や Vivaldi のブロッカーを無効化しましたが、プログレスバーの不具合は修正されませんでした Stylisy の YouTube Live Borderless と併用したときに問題が顕著化するようです。

YouTube Live Borderless を利用したい場合、[YouTube Video Resize Fix](https://greasyfork.org/en/scripts/457319-youtube-video-resize-fix)が必要です。YouTube Live BorderlessのYouTube WPRをONにすることもおすすめです。
