### ISSUE TITLE
Bug with description

### ISSUE THREAD

**Issue by Alex2036** [cyfung1031/Tabview-Youtube#24]
Hi, for a long time there is a problem with displaying information in the ''Description'' window 
What to do?

**Comment by Alex2036** [comment]
![Uploading Screen-1150.png…]()

**Comment by Alex2036** [comment]
![Screen-1150](https://github.com/cyfung1031/Tabview-Youtube/assets/100093524/75c4d445-bbfa-461b-be90-1ce6eb18dc42)

**Comment by cyfung1031** [comment]
https://greasyfork.org/en/scripts/470428-youtube-experiment-flags-tamer
