### ISSUE TITLE
playlist tab barely visible

### ISSUE THREAD

**Issue by ManabBala** [cyfung1031/Tabview-Youtube#34]
The playlist section is not showing all videos of the playlist. It's just showing just a horizontal crack. if you manage to place your cursor on the crack and scroll you will notice the list is being scrolled. So playlist element is still present under the front view window. maybe some css issue.

my quick fix:
apparently adding a height property (i did 100vh) to this element solved my issue.
```js
<div id="container" class="style-scope ytd-playlist-panel-renderer">...</div>
```
## Tampermonkey fix:
```js
// temporary fix for Tabview extension
GM_addStyle(`
  ytd-playlist-panel-renderer { 
     height: 100vh
}
`);
```

![image](https://github.com/cyfung1031/Tabview-Youtube/assets/94683653/37bb6dbf-9d07-491e-a8cb-26b245f32d3b)

**Comment by cyfung1031** [comment]
Updated. Please check again.

Some are just temporary fixes. To be further reviewed.

**Comment by ManabBala** [comment]
fixed the issue
