### ISSUE TITLE
[Request] Hide the comments tab when comments is disabled for that specific video

### ISSUE THREAD

**Issue by olivertzeng** [cyfung1031/Tabview-Youtube#37]

**Comment by cyfung1031** [comment]
https://greasyfork.org/en/scripts/467638-tabview-youtube-design-customization

Added to the "Tabview Youtube Design Customization"
Install Stylus and the userstyle to hide it.

<img width="267" alt="Screen Shot 2024-04-30 at 20 22 13" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/5f942ee4-1a6e-4540-842a-9b334c34fd20">
