### ISSUE TITLE
Small text on the "Info" tab

### ISSUE THREAD

**Issue by terminatorOST** [cyfung1031/Tabview-Youtube#4]
Hi!
The text size on the "Info" tab is much smaller than on other tabs and the rest of the page.
Google Chrome, Tampermonkey, last versions.

**Comment by cyfung1031** [comment]
As the info texts are read in a smaller box, the texts have to be smaller for display.
Otherwise there will be too many line breaks.

**Comment by terminatorOST** [comment]
Is there a way to write it in the script (adding a line or something), so that I can enlarge it for myself?
I don't mind the line breaks :P

**Comment by cyfung1031** [comment]
Hi, text size adjustment feature added in 2.4.1
![text size adjustment feature added in 2.4.1](https://user-images.githubusercontent.com/44498510/174445242-54f66b61-199d-49fe-838f-cabff090135f.png)
