### ISSUE TITLE
Duplicate description

### ISSUE THREAD

**Issue by Alex2036** [cyfung1031/Tabview-Youtube#40]
On all the clips at the bottom, the description is duplicated, just like in the side tab. Is it possible to do something about it?
![Screen-1179](https://github.com/cyfung1031/Tabview-Youtube/assets/100093524/58fd6959-f71b-4f10-8c9a-eb642e60fd02)

**Comment by Alex2036** [comment]
@cyfung1031  you're welcome. Thank you for your work. We really appreciate it.

**Comment by cyfung1031** [comment]
Should have fixed now. Please check and let me know.

**Comment by Alex2036** [comment]
@cyfung1031 Sorry for the delay in responding. Now everything looks neat and in perfect order. 
If there are any other problems with the script, I will write to you.
