### ISSUE TITLE
Comment count is always 0

### ISSUE THREAD

**Issue by Katzenwerfer** [cyfung1031/Tabview-Youtube#44]
In all videos I've tested, the comment count is always set to 0, even though that isn't the actual case.
I've only been able to reproduce the issue on my main LibreWolf profile, so I haven't singled out what could be causing it.
Currently using violentmonkey
![image](https://github.com/cyfung1031/Tabview-Youtube/assets/53267697/396ee1a7-bc3e-44d3-8c6c-235c3dd3c127)

**Comment by Katzenwerfer** [comment]
Tested on private browsing and a container tab and it works fine.
Also tried a fresh profile and the comment count displays without issues.

**Comment by cyfung1031** [comment]
Click the three dots to change the page language.
Check which language is checked.

<img width="356" alt="Screen Shot 2024-06-09 at 1 36 17" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/bd8af7e6-566a-4bd5-ad7b-7cc214604e94">

<img width="426" alt="Screen Shot 2024-06-09 at 1 36 23" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/d33ce179-d743-4a16-bff0-76cebf269003">

**Comment by Katzenwerfer** [comment]
Supposedly it's set to "English (US)" on my end.
Also tried changing to other languages and regions, but same results.

**Comment by cyfung1031** [comment]
Have you disabled all other extensions / plugins?

**Comment by Katzenwerfer** [comment]
I did earlier today. Behavior persisted nonetheless.
Something else I tried was logging out of my account and surprisingly it worked.
I assume it's a problem with my account, but it doesn't make much sense to me.

**Comment by cyfung1031** [comment]
This is A/B testing I believe.
Some accounts will experience the new changes (which is unstable and subject to further changes)
and some accounts would not.

I have not yet experience this so I cannot fix this issue at this moment. Please wait.

**Comment by cyfung1031** [comment]
Updated. Please check whether it is solved or not.

**Comment by Katzenwerfer** [comment]
Seems to be working now, with a small caveat with abbreviated counts where it only displays the first digit.

![image](https://github.com/cyfung1031/Tabview-Youtube/assets/53267697/ef6dc75c-b9a2-4e2b-ba03-1acf15fa0e3e)

![image](https://github.com/cyfung1031/Tabview-Youtube/assets/53267697/c466e69b-d5ff-4e31-83ea-e7c917c0164c)

**Comment by cyfung1031** [comment]
I think I need your help to debug this issue.

1. Please open the Console in Developer Tool
( shortcut keys: "Cmd + Option + J" (on a Mac) or "Ctrl +Shift +J" (on Windows) )

2. Paste this to the typing and press enter
```js
(()=>{const {commentsCount, countText} =document.querySelector('#tab-comments ytd-comments-header-renderer').polymerController.data; return JSON.stringify({commentsCount, countText})})()
```

3. Copy the result and post it for my reference.

<img width="1466" alt="Screen Shot 2024-06-17 at 23 04 51" src="https://github.com/cyfung1031/Tabview-Youtube/assets/44498510/7d8f4be4-015f-4e15-aef2-4391165fa65f">

**Comment by Katzenwerfer** [comment]
Here it is
```
16:51:48.520 >> (()=>{const {commentsCount, countText} =document.querySelector('#tab-comments ytd-comments-header-renderer').polymerController.data; return JSON.stringify({commentsCount, countText})})()
16:51:48.562 <- '{"commentsCount":{"runs":[{"text":"2.5K"}]},"countText":{"runs":[{"text":"Comments"},{"text":" 2.5K"}]}}'
```
Also tried it in safe mode (no extensions and custom settings) and the output seems the same
```
16:56:39.255 >> (()=>{const {commentsCount, countText} =document.querySelector('ytd-comments-header-renderer').polymerController.data; return JSON.stringify({commentsCount, countText})})()
16:56:39.291 <- '{"commentsCount":{"runs":[{"text":"2.5K"}]},"countText":{"runs":[{"text":"Comments"},{"text":" 2.5K"}]}}'

**Comment by cyfung1031** [comment]
Updated. Please check whether it works for you or not.

**Comment by Katzenwerfer** [comment]
Working fine 👍 
![image](https://github.com/cyfung1031/Tabview-Youtube/assets/53267697/e15ad753-3525-4502-a678-76ddc95ccd66)
