### ISSUE TITLE
Info and Comments tabs are broken as of yesterday

### ISSUE THREAD

**Issue by Yoksven** [cyfung1031/Tabview-Youtube#5]
Yesterday Info and Comments tabs stopped showing any content. Both tabs are empty. Comments tab says "fetching" forever.

I saw that some update for this script went through yesterday, but it didn't seem to fix it (at least for me).
(I think problems have started before the update, so it's probably not the update that broke things, though I'm not 100% on that)

Love the script by the way. I hope it'll get fixed. And thanks for making it.

**Comment by cyfung1031** [comment]
Thanks for reporting.
This issue only occur after 3.0.1?
No issue when you are using the old version 2.12.3?
(https://greasyfork.org/en/scripts/428651-tabview-youtube?version=1115222)

What is your system OS and browser ?

**Comment by cyfung1031** [comment]
There are some updates in v3.0.4.
Please update to see whether it helps or not.

**Comment by Yoksven** [comment]
My version says 3.0.5 and the problem is still there. And yes, before a couple of days ago I didn't had any problems.

I'm using Windows 7 and Firefox 88 (I know they're both outdated, but I'm that type of guy who sticks with the versions he likes; I'll probably be forced to update at some point...).

**Comment by Yoksven** [comment]
I did some investigating. Everything works in Chrome, but doesn't work in the latest Waterfox (Firefox fork), which means it's either a Firefox problem or Firefox's comparability with Windows 7 problem (which did happened in the past).

And also, it does "show" comments and description, but not in the tabs. They are below the video, where they usually are (but now they are in a small scrollable div).

**Comment by cyfung1031** [comment]
Any error message shown in the Firefox Dev Tools?

**Comment by cyfung1031** [comment]
Can you try to change the code "const DEBUG_LOG = false" into "const DEBUG_LOG = true"?

And screen capture the Dev Tools Console log messages. Just open the youtube link and click nothing.

**Comment by cyfung1031** [comment]
And what is the tampermonkey version you are using?

**Comment by Yoksven** [comment]
4.18.0. I assume it's the latest.

Here's [the log](https://i.ibb.co/y4dhX9r/log.jpg).

**Comment by cyfung1031** [comment]
Firefox 88 can use 4.18.0?
Waterfox classic with Tampermonkey 4.8.5847 can use without any issue.
I guess Tampermonkey 4.8.5847 will help for your case also.

**Comment by cyfung1031** [comment]
Bug fixed. Please install v3.3.0 to see whether it works or not.

**Comment by Yoksven** [comment]
Updated the script (by the way, couldn't update through Tampermonkey's dashboard, update button grayed out, so I grabbed it from greasy fork). And it still doesn't work. While I was at it, I tried downgrading to 2.12.2 version of the script and it worked just fine.

I'll try Tampermonkey 4.8.5847 just for the sake of the experiment, but even if it does make the latest version of the script work I'd rather have a downgraded script then a downgraded monkey.

**Comment by Yoksven** [comment]
Tried downgrading the monkey and using the latest script. Didn't worked for me. I don't know. Maybe something about my outdated setup is a problem. But the 2.12.2 works for me, so, maybe I'll just use that.

**Comment by cyfung1031** [comment]
Could you please try v3.6.0 and see whether it works for you or not?

https://greasyfork.org/en/scripts/428651-tabview-youtube

**Comment by Yoksven** [comment]
> Could you please try v3.6.4 and see whether it works for you or not?
> 
> https://greasyfork.org/en/scripts/428651-tabview-youtube

Sorry. I wrote a reply, but now it's not here (maybe I forgot to send it?... i don't remember). But whatever the case, I did tried it and it does work! I don't know why my comment about it isn't here, but, oh well. And the latest 3.7.6 also works.

Thanks for the fix!
