### ISSUE TITLE
Permanent comment tab

### ISSUE THREAD

**Issue by Alex2036** [cyfung1031/Tabview-Youtube#9]
Hello tell me if there is any way to make a tab with comments opened permanently?

**Comment by cyfung1031** [comment]
Currently no such a feature.

**Comment by Alex2036** [comment]
> Currently no such a feature.

Will this feature be available soon ?

**Comment by cyfung1031** [comment]
No plan to implement this feature.
By the way if you watch the videos in the same page, the comment tab will not be switched to videos tab when the next video is played.

**Comment by Alex2036** [comment]
> No plan to implement this feature. By the way if you watch the videos in the same page, the comment tab will not be switched to videos tab when the next video is played.
Too bad, of course, it would have been very convenient.
I know about this possibility, but it's not enough...

**Comment by Alex2036** [comment]
> No plan to implement this feature. By the way if you watch the videos in the same page, the comment tab will not be switched to videos tab when the next video is played.

Too bad, of course, it would have been very convenient.
I know about this possibility, but it's not enough...

**Comment by cyfung1031** [comment]
Please check the latest version.

**Comment by Alex2036** [comment]
> Please check the latest version.

Hello, I have not noticed any changes. May I ask what changes you made?

After upgrading to version 4.4.4, the tab is still switched by default and the "_comments_" tab is not saved after refreshing the page. I thought you wanted to and made the changes to your script that we talked about above)

**Comment by cyfung1031** [comment]
> > Please check the latest version.
> 
> Hello, I have not noticed any changes. May I ask what changes you made?
> 
> After upgrading to version 4.4.4, the tab is still switched by default and the "_comments_" tab is not saved after refreshing the page. I thought you wanted to and made the changes to your script that we talked about above)

<img width="465" alt="Screen Shot 2023-02-07 at 15 56 26" src="https://user-images.githubusercontent.com/44498510/217170454-62f76d6e-950f-4188-9e49-f09e565b8949.png">

Option is added

**Comment by Alex2036** [comment]
> > > Please check the latest version.
> > 
> > 
> > Hello, I have not noticed any changes. May I ask what changes you made?
> > After upgrading to version 4.4.4, the tab is still switched by default and the "_comments_" tab is not saved after refreshing the page. I thought you wanted to and made the changes to your script that we talked about above)
> 
> <img alt="Screen Shot 2023-02-07 at 15 56 26" width="465" src="https://user-images.githubusercontent.com/44498510/217170454-62f76d6e-950f-4188-9e49-f09e565b8949.png">
> 
> Option is added
> 
> https://greasyfork.org/en/scripts/428651-tabview-youtube

Got it. Figured it out. Excellent.
Thank you so much for this opportunity.
If I have any ideas or suggestions. I can write to you about it again, can't I?)

**Comment by cyfung1031** [comment]
sure.

**Comment by cyfung1031** [comment]
further discussion shall be as a separate issue
